### ISSUE TITLE
Crear modelo de datos para tablas Unidad y Periodos 

### ISSUE THREAD

**Issue by AlaskaRising** [udistrital/parametros_estandar_crud#1]
Dado el análisis realizado sobre las tablas unidad y periodos se decide crear una nueva API para estas tablas ya que no pertenecen a ningún esquema en concreto, la  API se define como  parametros_estandar. De esta forma, se deben realizar las siguientes actividades

- [x] Crear modelo de datos para las tablas de unidad y periodos
- [x] Revisión por parte de DBA de los Scripts de las tablas propuestas
- [x] Crear archivos de Beego Migrate para creación de schema y tablas

**Comment by mariaortiz0401** [comment]
Queda pendiente hasta reunión con Académica, Arquitectura y DBAs para aprobación final de tablas.

**Comment by AlaskaRising** [comment]
En la reunión con DBA's y Arquitectura se acordó usar el siguiente modelo:
![](https://raw.githubusercontent.com/udistrital/parametros_estandar_crud/dev/sql/parametros_estandar_v2.png)

y manejar los periodos como tipo_unidad, ademas de agregar una tabla periodo para información mas especifica de fechas de vigencia.

**Comment by nodier25** [comment]
se verifica los cambios que se sugieren al modelo esta todo ok

**Comment by AlaskaRising** [comment]
Las tablas de tipo_unidad, unidad y periodo, revisadas por arquitectos y dba's quedan desplegadas en ambiente Test.
